-- 테이블 생성 --
CREATE TABLE my_balance_sheets (
	YEAR                    INT  NOT NULL,
    MONTH                   INT  NOT NULL,
	CASH                    INT  NOT NULL  DEFAULT 0,
    INVESTMENT              INT  NOT NULL  DEFAULT 0,
    OTHERS                  INT  NOT NULL  DEFAULT 0,
    SHORT_TERM_LIABILITIES  INT  NOT NULL  DEFAULT 0,
    LONG_TERM_LIABILITIES   INT  NOT NULL  DEFAULT 0,
    DEPOSIT                 INT  NOT NULL  DEFAULT 0,
    RETAINED_EARNINGS       INT  NOT NULL  DEFAULT 0,
	PRIMARY KEY(YEAR, MONTH)
);

-- 연 단위(3년) 데이터 검색 (* 파라미터 필요 없음)
SELECT  YEAR AS PERIOD , 
        CASH , 
        INVESTMENT ,
        OTHERS ,
        IFNULL((CASH + INVESTMENT + OTHERS), 0) AS TOTAL_ASSETS ,
        SHORT_TERM_LIABILITIES , 
        LONG_TERM_LIABILITIES , 
        IFNULL((SHORT_TERM_LIABILITIES + LONG_TERM_LIABILITIES), 0) AS TOTAL_LIABILITIES ,
        DEPOSIT , 
        RETAINED_EARNINGS , 
        IFNULL((SHORT_TERM_LIABILITIES + LONG_TERM_LIABILITIES + DEPOSIT + RETAINED_EARNINGS), 0) AS TOTAL_LIABILITIES_AND_EQUITY,
		IFNULL(((SHORT_TERM_LIABILITIES + LONG_TERM_LIABILITIES) / (DEPOSIT + RETAINED_EARNINGS) * 100), 0) AS DEBT_RATE
FROM    my_balance_sheets 
WHERE   (YEAR <= YEAR(NOW())-1 AND MONTH = 12) 
		AND (YEAR >= YEAR(NOW())-2 AND MONTH=12)
        OR (YEAR = YEAR(NOW()) AND MONTH = MONTH(NOW()))
ORDER BY YEAR;

-- 분기 단위(4쿼터) 데이터 검색 (파라미터 : YEAR)
SELECT  CONCAT((MONTH/3 + ''), 'Q') AS PERIOD ,
        CASH , 
        INVESTMENT ,
        OTHERS ,
        IFNULL((CASH + INVESTMENT + OTHERS), 0) AS TOTAL_ASSETS ,
        SHORT_TERM_LIABILITIES , 
        LONG_TERM_LIABILITIES , 
        IFNULL((SHORT_TERM_LIABILITIES + LONG_TERM_LIABILITIES), 0) AS TOTAL_LIABILITIES ,
        DEPOSIT , 
        RETAINED_EARNINGS , 
        IFNULL((SHORT_TERM_LIABILITIES + LONG_TERM_LIABILITIES + DEPOSIT + RETAINED_EARNINGS), 0) AS TOTAL_LIABILITIES_AND_EQUITY,
		IFNULL(((SHORT_TERM_LIABILITIES + LONG_TERM_LIABILITIES) / (DEPOSIT + RETAINED_EARNINGS) * 100), 0) AS DEBT_RATE
FROM    my_balance_sheets 
WHERE   (YEAR = ?) 
		AND (MONTH = 3 OR MONTH = 6 OR MONTH = 9 OR MONTH = 12) 
ORDER BY MONTH DESC;

-- 월 단위(3개월) 데이터 검색 (파라미터 : YEAR, QUARTER(1~4))
SELECT  (CASE WHEN MONTH = 1 THEN 'Jan' 
              WHEN MONTH = 2 THEN 'Feb'
              WHEN MONTH = 3 THEN 'Mar'
              WHEN MONTH = 4 THEN 'Apr'
              WHEN MONTH = 5 THEN 'May'
              WHEN MONTH = 6 THEN 'Jun'
              WHEN MONTH = 7 THEN 'Jul'
              WHEN MONTH = 8 THEN 'Aug'
              WHEN MONTH = 9 THEN 'Sep'
              WHEN MONTH = 10 THEN 'Oct'
              WHEN MONTH = 11 THEN 'Nov'
              WHEN MONTH = 12 THEN 'Dec'
		 END) AS PERIOD , 
         CASH , 
         INVESTMENT ,
         OTHERS ,
         IFNULL((CASH + INVESTMENT + OTHERS), 0) AS TOTAL_ASSETS ,
         SHORT_TERM_LIABILITIES , 
         LONG_TERM_LIABILITIES , 
         IFNULL((SHORT_TERM_LIABILITIES + LONG_TERM_LIABILITIES), 0) AS TOTAL_LIABILITIES ,
         DEPOSIT , 
         RETAINED_EARNINGS , 
         IFNULL((SHORT_TERM_LIABILITIES + LONG_TERM_LIABILITIES + DEPOSIT + RETAINED_EARNINGS), 0) AS TOTAL_LIABILITIES_AND_EQUITY,
		 IFNULL(((SHORT_TERM_LIABILITIES + LONG_TERM_LIABILITIES) / (DEPOSIT + RETAINED_EARNINGS) * 100), 0) AS DEBT_RATE
FROM     my_balance_sheets 
WHERE    (YEAR = ?)
		 AND (MONTH >= ?*3-2 AND MONTH <= ?*3) 
ORDER BY MONTH DESC;
